source "https://rubygems.org"
git_source(:rd) { "https://github.com/Rails-Designer/#{it}" }

gem "perron", rd: "perron"
gem "rails", "~> 8.1.3"
gem "commonmarker", "~> 2.8.2"
gem "importmap-rails", "~> 2.2.3"
gem "propshaft", "~> 1.3.2"
gem "puma", "~> 8.0.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end

gem "rails_icons", "~> 1.9"
